# Generated by Django 4.2.13 on 2024-05-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'), ('whc_officer', 'Can access officer side')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Acls',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('eve_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eveonline.evecharacter')),
                ('member_state', models.IntegerField(choices=[(0, 'Not A Member'), (1, 'Applied'), (2, 'Rejected'), (3, 'Accepted')], default=0)),
                ('reject_reason', models.IntegerField(choices=[(0, 'Not Rejected'), (1, 'Insufficient Skills'), (2, 'Withdrawn Application'), (3, 'Removed From Community'), (99, 'Undisclosed')], default=0)),
                ('reject_timeout', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Applications',
                'ordering': ['eve_character__character_name'],
            },
        ),
        migrations.CreateModel(
            name='KnownAclAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_character', models.ManyToManyField(to='eveonline.evecharacter')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='whctools.acls')),
            ],
        ),
    ]
