# Generated by Django 4.2.13 on 2024-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whctools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='reject_reason',
            field=models.IntegerField(choices=[(0, 'Not Rejected'), (1, 'Insufficient Skills'), (2, 'Withdrawn Application'), (3, 'Removed From Community'), (4, 'Left Alliance'), (99, 'Undisclosed')], default=0),
        ),
    ]
