# Generated by Django 4.2.13 on 2024-05-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('whctools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acl',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('characters', models.ManyToManyField(to='eveonline.evecharacter')),
            ],
        ),
        migrations.RemoveField(
            model_name='knownaclaccess',
            name='eve_character',
        ),
        migrations.RemoveField(
            model_name='knownaclaccess',
            name='name',
        ),
        migrations.DeleteModel(
            name='Acls',
        ),
        migrations.DeleteModel(
            name='KnownAclAccess',
        ),
    ]
