# Generated by Django 4.0.10 on 2024-05-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whctools", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applications",
            options={
                "ordering": ["eve_character__character_name"],
                "verbose_name_plural": "Applications",
            },
        ),
    ]
