# Generated by Django 4.2.13 on 2024-06-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whctools', '0002_alter_applications_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclhistory',
            name='reason_for_change',
            field=models.IntegerField(choices=[(0, 'No Change / Initial Acceptance'), (1, 'Application Accepted'), (2, 'Character left Uni or Uni Affiliated'), (3, 'Character was removed from ACL by an Officer'), (4, 'Left on their own choice'), (99, 'Other: See details')], default=0),
        ),
    ]
