# Generated by Django 4.2.13 on 2024-05-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('whctools', '0002_acl_remove_knownaclaccess_eve_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACLHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_change', models.DateField()),
                ('old_state', models.IntegerField(choices=[(0, 'Not A Member'), (1, 'Applied'), (2, 'Rejected'), (3, 'Accepted')], default=0)),
                ('new_state', models.IntegerField(choices=[(0, 'Not A Member'), (1, 'Applied'), (2, 'Rejected'), (3, 'Accepted')], default=0)),
                ('changed_by', models.CharField(blank=True, max_length=225)),
                ('acl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='whctools.acl')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecharacter')),
            ],
        ),
    ]
