# Generated by Django 4.2.13 on 2024-05-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whctools', '0003_aclhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclhistory',
            name='date_of_change',
            field=models.DateTimeField(),
        ),
    ]
