# Generated by Django 4.2.13 on 2024-06-05 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whctools', '0003_aclhistory_reason_for_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='reject_reason',
            field=models.IntegerField(choices=[(0, 'Not Rejected'), (1, 'Insufficient Skills'), (2, 'Withdrawn Application'), (3, 'Removed From Community'), (4, 'Left Alliance'), (5, 'Voluntarily Left'), (99, 'Undisclosed')], default=0),
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_change', models.DateTimeField(auto_now_add=True)),
                ('old_state', models.IntegerField(choices=[(0, 'Not A Member'), (1, 'Applied'), (2, 'Rejected'), (3, 'Accepted')], default=0)),
                ('new_state', models.IntegerField(choices=[(0, 'Not A Member'), (1, 'Applied'), (2, 'Rejected'), (3, 'Accepted')], default=0)),
                ('reject_reason', models.IntegerField(choices=[(0, 'Not Rejected'), (1, 'Insufficient Skills'), (2, 'Withdrawn Application'), (3, 'Removed From Community'), (4, 'Left Alliance'), (5, 'Voluntarily Left'), (99, 'Undisclosed')], default=0)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_history', to='whctools.applications')),
            ],
        ),
    ]
