# Generated by Django 4.2.13 on 2024-06-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whctools', '0005_alter_applicationhistory_options_acl_skill_plans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acl',
            old_name='skill_plans',
            new_name='skill_sets',
        ),
    ]
