# Generated by Django 4.2.14 on 2024-08-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('whctools', '0006_rename_skill_plans_acl_skill_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='acl',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
