# Generated by Django 4.2.20 on 2025-03-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whctools", "0008_allow_empty_acl_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WelcomeMail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail_content", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
